f1=open('../../../PycharmProjects/PythonProject/output.txt', 'w')
a=input('Enter text to write to the file:')
a1=f1.write(a+'\n')
f1.close()
f1=open('../../../PycharmProjects/PythonProject/output.txt', 'a')
b=input('Enter additional text to append:')
b2=f1.write(b)
f1.close()
f1=open('../../../PycharmProjects/PythonProject/output.txt', 'r')
print('Final content of output,txt:\n')
c=f1.read()
print(c)
f1.close()
